{{- if and .Values.rbac.enabled (eq .Values.mode "llminferenceservice") }}
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{ .Values.llminferenceservice.gateway.name }}-authn
  namespace: {{ .Values.llminferenceservice.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  rules:
    authentication:
      kubernetes-user:
        credentials: {}
        kubernetesTokenReview:
          audiences:
          - https://kubernetes.default.svc
          - {{ .Values.llminferenceservice.gateway.name }}-sa
        metrics: false
        priority: 0
    authorization:
      inference-access:
        kubernetesSubjectAccessReview:
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            name:
              expression: request.path.split("/")[2]
            namespace:
              expression: request.path.split("/")[1]
            resource:
              value: llminferenceservices
            subresource: {}
            verb:
              value: get
          user:
            expression: auth.identity.user.username
        metrics: false
        priority: 1
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.llminferenceservice.gateway.name }}
{{- end }}
